service: chatwork-cloudwatch

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1

  environment:
    CHATWORK_API_KEY:
    CHATWORK_HEADER: X-ChatWorkToken
    CHATWORK_ROOM_ID: 88213490
    CHATWORK_URL: https://api.chatwork.com/v2

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  hello:
    handler: handler.hello

